
stages:
  - deploy-eks-cluster

deploy-gke-cluster:
  stage: deploy-gke-cluster
  when: manual
  trigger:
    include:
      - local: google-cloud/.gitlab-ci.yml
    strategy: depend

deploy-eks-cluster:
  stage: deploy-eks-cluster
  when: manual
  trigger:
    include:
      - local: aws/.gitlab-ci.yml
    strategy: depend

